### PR TITLE
Add wellknown support in the login flow

### LINKED ISSUE #476: Support homeserver discovery from MXID
When the full MXID is entered as the username, RiotX should try to do a homeserver discovery (via well-known) and fill the homeserver URL field correspondigly if the discovery was successful.

### PR DESCRIPTION
**Pull request by bmarty**
Draft because we wait for status from @nadonomy about the UX

Fixes #476 

image

image

Error case:
image

Bad credential case:

image

### CODE REVIEW

**Comment by dkozel** [comment]
Does this include resolving the homeserver on the first screen (before user/password) using well-known?

image

```
[dkozel@wyvern ~] wget gnuradio.org/.well-known/matrix/client
--2020-04-26 17:48:46--  http://gnuradio.org/.well-known/matrix/client
Resolving gnuradio.org (gnuradio.org)... 140.211.167.19
Connecting to gnuradio.org (gnuradio.org)|140.211.167.19|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gnuradio.org/.well-known/matrix/client [following]
--2020-04-26 17:48:46--  https://gnuradio.org/.well-known/matrix/client
Connecting to gnuradio.org (gnuradio.org)|140.211.167.19|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.gnuradio.org/.well-known/matrix/client [following]
--2020-04-26 17:48:47--  https://www.gnuradio.org/.well-known/matrix/client
Resolving www.gnuradio.org (www.gnuradio.org)... 140.211.167.19
Connecting to www.gnuradio.org (www.gnuradio.org)|140.211.167.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 77 [application/octet-stream]
Saving to: ‘client’

client              100%[===================>]      77  --.-KB/s    in 0s      

2020-04-26 17:48:48 (3.39 MB/s) - ‘client’ saved [77/77]

[dkozel@wyvern ~] cat client 
{ "m.homeserver": { "base_url": "https://gnuradio.matrix.ungleich.cloud" } }
```

Entering `gnuradio.matrix.ungleich.cloud` works. The `server` well-known file is also setup.

**Comment by bmarty** [comment]
@dkozel 

> Does this include resolving the homeserver on the first screen (before user/password) using well-known?

No, the homeserver will be deduced from the entered userId. Ex: `@bob:gnuradio.org`, the well-known request will be done on `https://gnuradio.org/.well-known/matrix/client`

Regarding the 301, I'm investigating the point

**Comment by dkozel** [comment]
As far as I can tell it is required to enter the home server manually if not using matrix.org or modular homeservers? That's at least the most obvious flow, every single dev in GNU Radio has tried that while testing our new setup.

**Comment by bmarty** [comment]
Ok @dkozel , I've implemented using wellknown at the step where entering the homeserver URL in 
fab644d. It should cover your use case, i.e. when entering `gnuradio.org` as a homeserver url, it will be resolved to `gnuradio.matrix.ungleich.cloud`.

This PR originally adds an alternative way to get connected to your account, just by entering a (full) userId and a password, and without entering explicitly the homeserver URL

**Pull request merged**
