### PR TITLE
set homeserver field when populating room directory list

### LINKED ISSUE #807: matrix.org directory not working from different homeserver
RiotX currently always queries the users homeserver directory.

### PR DESCRIPTION
**Pull request by Bubu**
fixes #807

### Pull Request Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 16
- [ ] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [x] Pull request updates [CHANGES.md](https://github.com/vector-im/riotX-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

### CODE REVIEW

**Comment by bmarty** [comment]
Thanks for the PR.
I think it's ok, but could you please precise what was the issue and why this PR fixes it?
Thanks

**Comment by Bubu** [comment]
I added steps to reproduce here: https://github.com/vector-im/riotX-android/issues/807#issuecomment-571136081

The homeserver variable was always `null` when querying the room-directory which results in only ever querying your own homeserver.

This PR add the correct homeserver field when populating the list of available homeserver directories from here: https://github.com/vector-im/riotX-android/blob/develop/vector/src/main/res/values/config.xml#L20

**Comment by Bubu** [comment]
How do you want to handle the CHANGES.md file? There will always be conflicts here.

**Comment by bmarty** [comment]
Ok, thanks. I handle the conflict on CHANGES.md, don't worry

**Pull request merged**
