### PR TITLE
Make tasks responsible for dispatching.

### PR DESCRIPTION
**Pull request by Dominaezzz**
Signed-off-by: Dominic Fischer <dominicfischer7@gmail.com>

### Pull Request Checklist

- [ ] Changes has been tested on an Android device or Android emulator with API 16
- [ ] UI change has been tested on both light and dark themes
- [x] Pull request is based on the develop branch
- [ ] Pull request updates [CHANGES.md](https://github.com/vector-im/riotX-android/blob/develop/CHANGES.md)
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

In this PR I have made `Task`s responsible for which dispatcher they run in.
In terms of coroutines, it doesn't make sense for caller to dictate where a task should execute, the task should know it needs to place blocking IO in the IO dispatcher, crypto in the crypto dispatcher, etc.
In some cases, tasks might need to use mutliple dispatchers depending on what it is doing, in which case, `executionThread` stops making sense.

Somewhat related:
I also noticed that `Dispatchers.IO` (dynamic 64 threads) is used for everything instead of `Dispatchers.Default` (fixed n threads, n == number of cores). Doing this might be less efficient, since threads won't be recycled, app becomes more resource heavy.

### CODE REVIEW

**Comment by ganfra** [comment]
Thanks for you work. You are talking about using Default but in your PR you set computation as the "default" one?

**Comment by Dominaezzz** [comment]
Yes I use computation as the default but computation is set to `Dispatchers.IO`.
Computation should point to `Dispatchers.Default` but I haven't made any changes regarding that in this PR because I wanted to know why it was used before changing it.

**Comment by ganfra** [comment]
Actually, most of the tasks are doing network calls and db insertions, so it was more convenient to use IO by default. But as you said, each task should know which dispatcher to use, so shouldn't we totally remove it from TaskExecutor?

**Comment by Dominaezzz** [comment]
Good point. I'll just remove it.

**Comment by Dominaezzz** [comment]
I've rearranged to make sure the callback dispatcher is not as "busy". Also removed dispatcher.

**Pull request closed without merging**
