### PR TITLE
Use Context#withStyledAttributes extension function.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ This function is more concise and ensures `recycle()` is always invoked.
+ Sources: https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-preference-release/core/core-ktx/src/main/java/androidx/core/content/Context.kt#52

Signed-off-by: Tobias Preuss tobias.preuss@googlemail.com

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Flaky Android tests .. :parrot:

**Comment by bmarty** [comment]
> Flaky Android tests .. 🦜

Yes, we will fix that, thanks :)

**Comment by johnjohndoe** [comment]
Magically self-healing :)

**Comment by johnjohndoe** [comment]
Thanks. Feel free to rebase the branch before merging it to facilitate a linear history. Let me know if I should do this.

**Comment by johnjohndoe** [comment]
Rebased. Moved the CHANGES entry to the new version block.

**Pull request merged**
